### PR TITLE
ee: use json sources to add directorships and bfo

### PR DESCRIPTION
**Pull request by simonwoerpel**
it's not perfect yet but much more data

### CODE REVIEW

**Comment by pudo** [comment]
Can you describe how it's not perfect? ;)

**Comment by pudo** [comment]
Ah and can you remember to update the metadata description?

**Comment by simonwoerpel** [comment]
> Ah and can you remember to update the metadata description?

i think i did

**Comment by simonwoerpel** [comment]
> Can you describe how it's not perfect? ;)

- deduplication of officer entities is not perfect
- there can be multiple Ownership intervals between 1 officer and 1 entity with different dates and role specification:
  -  "otsene osalus" (direct holding) -> comes from the bfo data source but without more context data
  -  "Osanik" (translated as "associate") but with shareholding/percentage data -> comes from the officers data sources
dont't know if this needs to be consolidated somehow?

in any case, the provided json is somehow a bit unintuitive and inconsistent and maybe further sanity checks or production use of this dataset may raise more questions, but for now it looks not too bad

**Comment by simonwoerpel** [comment]
> Can you describe how it's not perfect? ;)

ah, and there are many Directorship intervals with role "Asutaja" which translates to "Founder", do we want to keep them?

**Comment by pudo** [comment]
Yes, let's. Might be in the Russian sense of "major shareholder" ....

**Review by pudo — APPROVED** [review]

**Pull request merged**
